//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerId { get; set; }
        public string AnswerTitle { get; set; }
        public Nullable<int> AnswerIsCorrect { get; set; }
        public int QuestionId { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
