//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int QuestionId { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionDescription { get; set; }
        public string QuestionAnswer { get; set; }
        public int QuestionTestId { get; set; }
    
        public virtual Tests Tests { get; set; }
    }
}
